### ISSUE TITLE
Chapter 4, Section 9 Page 275 "that named showingTintSelector" Missing "is"?

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec009-SwiftUIKickstart#11]
"We add a State property that is a Bool that named showingTintSelector..."

Meant to be "that is named "?

**Comment by axello** [comment]
Or leave the word 'that' out :-), otherwise double-that.
(But I'm not the editor 👍 )

**Comment by editorscut** [comment]
Removed "that" thank you
