### ISSUE TITLE
Chapter 5, Section 9, A Button that doesn't work?

### ISSUE THREAD

**Issue by axello** [editorscut/ec009-SwiftUIKickstart#25]
Hi, on page 367, chapter 5.9, you have a section header
“Section(header: Text("A Button that doesn't work"))”

But I politely disagree: the button action works fine. It just does not look like a button, but what does nowadays, with Flat UI?. 

Also it is not updating its status, but
→ The action is still executed fine and the list is updated correctly.

I guess it is philosophical: what is the purpose of a button, to be shiny or to act?

**Comment by editorscut** [comment]
I was being too flip - changed it to "A Button". You're right it distracts from what I'm teaching. Thank you

**Comment by editorscut** [comment]
Also - can I add your name to tech reviewers? If so, please email me with how you'd like your name to appear (lessens but doesn't eliminate the likelihood that I type it wrong.)

**Comment by axello** [comment]
I would be humbly honoured!
