### ISSUE TITLE
Chapter 1, Section 6

### ISSUE THREAD

**Issue by elkraneo** [editorscut/ec009-SwiftUIKickstart#28]
The link used in
>“You can find all of the code for this book at https://github.com/editorscut/ec009-swiftui-kickstart”

should point to https://github.com/editorscut/ec009-SwiftUIKickstart

also in
> “Submit your errata here”

currently points to https://github.com/editorscut/ec009-swift-kickstart-2/issues, and should be https://github.com/editorscut/ec009-SwiftUIKickstart/issues

**Comment by editorscut** [comment]
Thank you - fixed
