### ISSUE TITLE
Accessibility

### ISSUE THREAD

**Issue by elkraneo** [editorscut/ec009-SwiftUIKickstart#29]
Daniel, really enjoyed your book (like the way you order logically instead sequentially and the way it iterates through samples), but it calls my attention that there isn't a single reference to accessibility on it. Think will be really interesting/useful to have some inputs on how to use the new API when the automatically generated accessibility elements are not enough.

~~One small example could be how to control SFSymbols resizing when used on `tabItem` and previewed with different size categories like `accessibilityExtraExtraExtraLarge`)~~ this can be accomplished with the non so intuitive use of font sizes on Image, for example: `Image(systemName: "paperplane").font(.system(size: 22))`

**Comment by editorscut** [comment]
Thank you - let me leave this open while I think about how and where to address this.

**Comment by dimsumthinking** [comment]
I added a section. And then because I forgot to close this issue I added a similar section again. Reduced to just one - hope it addresses this issue. Thank you.
