### ISSUE TITLE
Chapter 5, Section 11 - Record Mood button records value not reflected in the slider

### ISSUE THREAD

**Issue by michaeljbishop** [editorscut/ec009-SwiftUIKickstart#32]
I believe there is a bug in the resulting program at the end of the chapter.

Steps to reproduce:

1. Run the app
2. Move the slider to a value other than `2.0` (say, `2.5`). Add context. Tap the “Record Mood” button.
3. Note the value of the slider. _Without touching the slider again_, add a new context. Tap the “Record Mood” button a second time.
4. Look in the history tab. The mood you just recorded will have the `2.0` value, not the value of the slider.

This is because the value of`MoodInputPresenter.rating` was reset to `2.0` in the `reset()` call, but the slider has a value independent of that. The slider only updates the `MoodInputPresenter.rating` when it has been moved, but we made sure not to move it in the reproduction steps in between presses to the “Record Mood” button.

**Comment by dimsumthinking** [comment]
Thank you fixed - solution is much simpler thank you. Will be in next version
