### ISSUE TITLE
Chapter 2, Section 4 (some)

### ISSUE THREAD

**Issue by donnywals** [editorscut/ec009-SwiftUIKickstart#33]
Let me start by saying I really enjoyed the book. I didn't see the following until I tried to use it as a reference for using opaque return types in my own code.

The following is mentioned about some and opaque return types:

```
“View is a protocol. It feels like you should just be able to announce that body returns View and then it doesn't matter what sort of View you return. Swift doesn't allow protocols as a return type”
```

However, the issue a little bit more nuanced. We can use protocols as return types just fine:

```
protocol AProtocol {}

func doThing() -> AProtocol {
}
```

Swift will happily compile the code above. It's when we add an associated type to `AProtocol ` that we need `some`:

```
protocol AProtocol {
  associatedtype AThing
}

// this doesn't compile
func doThing() -> AProtocol {
}

// this does
func doThing() -> some AProtocol {
}
```

 I'm still trying to figure out what opaque result types are exactly and what problems they solve but so far it appears that the compiler wants to understand what an item's associated type is when it's used as a return type. Similar to how `Array` can't be a return type because the compiler wants to know what the generic `Element` for the array should be. `some` seems to tell the compiler to ignore the associated type

```
protocol Generator {
  associatedtype GeneratedItem

  func generate() -> GeneratedItem
}

struct AGenerator: Generator {
  func generate() -> String {
    "Hello, World!"
  }
}

func createGenerator() -> some Generator {
  AGenerator()
}

let generator = createGenerator()
generator.generate() // this returns Generator.GeneratedItem rather than String
```

Like I said I might be overlooking something but this is what I found while trying to figure out when I would need the `some` keyword in my own codebase.

**Comment by dimsumthinking** [comment]
Thanks - I hope I've addressed this. I enjoyed your write-up on the topic

**Comment by donnywals** [comment]
I just got around to reading the updated chapter. Looks good! Love the Airplane analogy, it works well.
