### ISSUE TITLE
Chapter 3, Section 9

### ISSUE THREAD

**Issue by brettha** [editorscut/ec009-SwiftUIKickstart#37]
In the completed example code it does not compile.  I think it's because in ValueView.swift, the property wrapper line is 
`@RoundedTo(1) var value: Double = 0`
but should be
`@ToTwoPlaces var value: Double = 0`

**Comment by editorscut** [comment]
Yes! Thank you for the correction. Sorry for that. I've fixed it in the update I'm pushing today.
