### ISSUE TITLE
Indenting

### ISSUE THREAD

**Issue by johnrnyquist** [editorscut/ec009-SwiftUIKickstart#38]
v0.5 of book. In Chapter 4: Section 5 the line of code is indented too much.
![image](https://user-images.githubusercontent.com/2531788/92977093-568b9680-f449-11ea-91d0-e05012a7e152.png)

**Comment by editorscut** [comment]
Thank you - this is temporarily moved to chapter 5 but will replaced in the chapter 5 rewrite
