### ISSUE TITLE
Front Matter

### ISSUE THREAD

**Issue by joecabrera** [editorscut/ec009-SwiftUIKickstart#53]
**Copyright:** do you want to change it to a rolling copyright date and include years when the book was revised (© 2019–2020)?

**Book Version:** update to the latest version numbers where needed. You may also want to change "released" to "originally released" if you want to keep that December date, or maybe change it to "revised Mmm DD, 20YY", or use both. Of course all this means just another thing to remember to update every time the book gets revised...

**Legal:** "Apple Inc" near the end of the penultimate paragraph needs a period.

**Comment by editorscut** [comment]
fixed. Thank you
