### ISSUE TITLE
Chapter 3, Section 6, Page 186 "greeting: "Hey")"

### ISSUE THREAD

**Issue by nwreg** [editorscut/ec009-SwiftUIKickstart#7]
Inside the GreetingLabel_Previews, we have 
GreetingLabel(greeting: "Hey") 

Was is supposed to be "Hey" for the text there?

-------
Addition: Same question in Page 192 
We have 
GreetingButton(greeting: .constant("Hey"))

**Comment by editorscut** [comment]
Thank you I've added an explanation in both places that I hope clarifies.
